services:
  db:
    image: postgres:16-alpine
    container_name: hafiyyan_betta_db
    environment:
      - POSTGRES_DB=hafiyyan_betta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: hafiyyan_betta_server
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hafiyyan_betta
      - JWT_SECRET=replace_with_random_secret
      - PGSSL=false
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '4000:4000'
    restart: unless-stopped

volumes:
  postgres_data: